dist: focal
jdk: oraclejdk11
language: java

install:
- sudo apt-get install -y rlwrap
- curl -O https://download.clojure.org/install/linux-install-1.10.1.727.sh
- chmod +x linux-install-1.10.1.727.sh
- sudo ./linux-install-1.10.1.727.sh

script: make test
after_success: make jar && make pub
